### ISSUE TITLE
Bug: Sorting doesn't work on tables with rowspans

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/popolo-viewer-sinatra#141]
We've turned it off explicitly for Finland, but we should make it work again.

See https://github.com/mysociety/popolo-viewer-sinatra/pull/122

**Comment by tmtmtmtm** [comment]
Adding label Design as per #150

**Comment by zarino** [comment]
My current thinking as to a minimum viable solution: **As soon as you sort the table manually, rowspans are removed.**

This would simply fire once, replacing the "rowspan" attribute on any cells it finds, and duplicating the cell onto subsequent lines below, as required.

@tmtmtmtm: Does that sound acceptable?

Aside: It would be *very* interesting to add Google Analytics event tracking to the sorting action, to see what proportion of visitors actually do it. Once we know that, we can appraise whether a more sophisticated solution is required.

**Comment by zarino** [comment]
> My current thinking as to a minimum viable solution: As soon as you sort the table manually, rowspans are removed.

Oh, looks like this is [exactly what Wikipedia does](http://en.wikipedia.org/wiki/Help:Sorting#Tables_with_complex_datarows). Notably *even they* don't bother with gluing repeated cells back together into rowspans once you've made your first sorting action.

**Comment by tmtmtmtm** [comment]
Yep — that's certainly an acceptable approach, for now at least. If we were to split this out into a standalone library, perhaps someone else might come along and add something better :)
