### ISSUE TITLE
Allow .avatar-list to have an extra line of content

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/popolo-viewer-sinatra#38]
Per discussion on https://github.com/mysociety/popolo-viewer-sinatra/pull/36, the Avatar List needs to be able to include extra content on the next line (e.g. a date range)

**Comment by tmtmtmtm** [comment]
This will also need to ensure that the column breaks don't happen between the lines:

![column breaking 2015-04-22 at 11 44 47](https://cloud.githubusercontent.com/assets/57483/7272722/1333f9ba-e8e5-11e4-9fee-212d3b16530c.png)

**Comment by zarino** [comment]
Tada! https://github.com/mysociety/popolo-viewer-sinatra/pull/42
