### ISSUE TITLE
Better styling for "This country doesn't have any terms data" blank slate message

### ISSUE THREAD

**Issue by zarino** [mysociety/popolo-viewer-sinatra#9]
Currently looks a bit rubbish when a country (eg: Wales) has no data about the dates different parliaments cover.

As well as explaining why the page is empty, the message should also, ideally, explain how to fix this problem (improve the data in PopIt!) – is that right, @tmtmtmtm?

**Comment by tmtmtmtm** [comment]
Yep, this will be a regular thing in lots of contexts (not just terms) — we should explain why we can't display anything, and what the Popolo data for that would look like, and probably give a link to an example of a Country with good data for that concept. 

In some cases we might even be able to fix up the data in PopIt for them, if they, for example were to give us a simple csv file of just that type of data to apply on top of what already exists. That's a little further down the line, but worth bearing in mind that it's quite likely that that's the sort of thing we might want to do here.

**Comment by zarino** [comment]
@tmtmtmtm: I've just made a simple layout from existing bits of styling, that you can start building your messaging off:

![screen shot 2015-04-17 at 14 12 13](https://cloud.githubusercontent.com/assets/739624/7202603/d8c3d660-e50b-11e4-9673-152e3ac09fea.png)

The wording obviously needs some work! I've assumed you'll want to keep the message short and then link to documentation elsewhere. Let me know if that's not right.

**Comment by tmtmtmtm** [comment]
@zarino: thanks. If I want to include example JSON inside the "you can fix this" section (as in #15), how should I style that? It looks wrong centered, and I tried to work around it in in the short term by just adding a `text-left` to the CSS to parallel the `text-center`, but I couldn't get it to work, and I suspect there's a much better way to do this sort of thing anyway.

**Comment by zarino** [comment]
@tmtmtmtm I've just pushed a change (https://github.com/mysociety/popolo-viewer-sinatra/commit/fe347cea031e626a393df86c3e7fa8f9fb33b9e9) that improves the rules regarding `<pre>` tags.

![screen shot 2015-04-20 at 14 44 47](https://cloud.githubusercontent.com/assets/739624/7231192/db9a0e24-e76b-11e4-8d96-cdbe02e4c661.png)

**Comment by tmtmtmtm** [comment]
@zarino Thanks — that looks much better!
